### ISSUE TITLE
options for keywordmap

### ISSUE THREAD

**Issue by bnomei** [jenstornell/kirby-keyword-map#8]
- do the `default` value work for `keywordmap`?
- could the `keywordmap` be extendend to read its options from another field/page/json [like the select field can](https://getkirby.com/docs/cheatsheet/panel-fields/select)?
- i would also like the `keywordmap` to be switchable to readonly mode.

**Comment by jenstornell** [comment]
I just tested it. My field is an extended `tags` field. That means that it can't read options from other fields:

https://getkirby.com/docs/cheatsheet/panel-fields/tags

I don't know why the `default` value does not work with my field but I've added an own issue for that.

`readonly` works but for it to be useful you first need to add keywords and then add readonly true. Else you have no keywords to work with.

I'm closing it because I've added an issue about the default value.
